name: kombong_genz
description: IoT Monitoring System - Pengabdian Masyarakat (Kombong GenZ)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # State Management
  flutter_riverpod: ^2.5.1

  # HTTP Client
  dio: ^5.4.3+1

  # MQTT Client
  mqtt_client: ^10.2.1

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # UI Components
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Font (Google Fonts - tidak perlu file TTF manual)
  google_fonts: ^6.2.1

  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  # Local Push Notification
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
